image:
  - Visual Studio 2019
  - Ubuntu

stack: python 3

environment:
  PY_DIR: C:\Python37-x64

init:
- cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%

install:
- python -m pip install -r requirements.txt
- python -m pip install -r requirements_build.txt

build_script:
  - python -m PyInstaller ssrando.spec
  - cp README.md dist
  - cp randomize.bat dist
  - cp setup.bat dist

artifacts:
  # pyinstaller puts the build exe here
  - path: dist
    name: dist
    type: zip